package im.hikaru.harness.llm.koog

/** llm-koog 转换与路由边界使用的稳定错误码。 */
object KoogLlmErrorCode {
    const val UNKNOWN_PROVIDER = "KOOG_UNKNOWN_PROVIDER"
    const val UNKNOWN_MODEL = "KOOG_UNKNOWN_MODEL"
    const val INVALID_STREAM_STATE = "KOOG_INVALID_STREAM_STATE"
    const val UNSUPPORTED_OPTION = "KOOG_UNSUPPORTED_OPTION"
    const val UNSUPPORTED_CONTENT = "KOOG_UNSUPPORTED_CONTENT"
    const val UNSUPPORTED_FINISH_REASON = "KOOG_UNSUPPORTED_FINISH_REASON"
    const val INVALID_USAGE = "KOOG_INVALID_USAGE"
    const val UNSUPPORTED_REASONING_CONTENT = "KOOG_UNSUPPORTED_REASONING_CONTENT"
    const val INVALID_REPLAY_STATE = "KOOG_INVALID_REPLAY_STATE"
    const val REPLAY_MAPPING_NOT_IMPLEMENTED =
        "KOOG_REPLAY_MAPPING_NOT_IMPLEMENTED"
    const val INVALID_TOOL_HISTORY = "KOOG_INVALID_TOOL_HISTORY"
    const val INVALID_TOOL_SCHEMA = "KOOG_INVALID_TOOL_SCHEMA"
    const val UNSUPPORTED_TOOL_SCHEMA = "KOOG_UNSUPPORTED_TOOL_SCHEMA"
}
