package im.hikaru.ruoyi.module.system.dal.mysql.oauth2

import im.hikaru.ruoyi.framework.mybatis.core.dataobject.BaseTable
import im.hikaru.ruoyi.module.system.dal.mysql.jsonStringList
import im.hikaru.ruoyi.module.system.dal.mysql.jsonStringMap
import org.jetbrains.exposed.v1.datetime.datetime

object OAuth2ClientTable : BaseTable("system_oauth2_client") { val id = long("id").autoIncrement("system_oauth2_client_seq"); val clientId = varchar("client_id",255); val secret = varchar("secret",255); val name = varchar("name",255); val logo = varchar("logo",255); val description = varchar("description",255).nullable(); val status = integer("status"); val accessTokenValiditySeconds = integer("access_token_validity_seconds"); val refreshTokenValiditySeconds = integer("refresh_token_validity_seconds"); val redirectUris = jsonStringList("redirect_uris"); val authorizedGrantTypes = jsonStringList("authorized_grant_types"); val scopes = jsonStringList("scopes").nullable(); val autoApproveScopes = jsonStringList("auto_approve_scopes").nullable(); val authorities = jsonStringList("authorities").nullable(); val resourceIds = jsonStringList("resource_ids").nullable(); val additionalInformation = varchar("additional_information",4096).nullable(); override val primaryKey=PrimaryKey(id) }
object OAuth2AccessTokenTable : BaseTable("system_oauth2_access_token") { val id=long("id").autoIncrement("system_oauth2_access_token_seq"); val userId=long("user_id"); val userType=integer("user_type"); val userInfo=jsonStringMap("user_info"); val accessToken=varchar("access_token",255); val refreshToken=varchar("refresh_token",32); val clientId=varchar("client_id",255); val scopes=jsonStringList("scopes").nullable(); val expiresTime=datetime("expires_time"); val tenantId=long("tenant_id"); override val primaryKey=PrimaryKey(id) }
object OAuth2RefreshTokenTable : BaseTable("system_oauth2_refresh_token") { val id=long("id").autoIncrement("system_oauth2_refresh_token_seq"); val userId=long("user_id"); val refreshToken=varchar("refresh_token",32); val userType=integer("user_type"); val clientId=varchar("client_id",255); val scopes=jsonStringList("scopes").nullable(); val expiresTime=datetime("expires_time"); val tenantId=long("tenant_id"); override val primaryKey=PrimaryKey(id) }
object OAuth2CodeTable : BaseTable("system_oauth2_code") { val id=long("id").autoIncrement("system_oauth2_code_seq"); val userId=long("user_id"); val userType=integer("user_type"); val code=varchar("code",32); val clientId=varchar("client_id",255); val scopes=jsonStringList("scopes").nullable(); val expiresTime=datetime("expires_time"); val redirectUri=varchar("redirect_uri",255).nullable(); val state=varchar("state",255); val tenantId=long("tenant_id"); override val primaryKey=PrimaryKey(id) }
object OAuth2ApproveTable : BaseTable("system_oauth2_approve") { val id=long("id").autoIncrement("system_oauth2_approve_seq"); val userId=long("user_id"); val userType=integer("user_type"); val clientId=varchar("client_id",255); val scope=varchar("scope",255); val approved=bool("approved"); val expiresTime=datetime("expires_time"); val tenantId=long("tenant_id"); override val primaryKey=PrimaryKey(id) }
